export const NUMBERS = [
	{ string: '1', value: 1 },
	{ string: 'one', value: 1 },
	{ string: '2', value: 2 },
	{ string: 'two', value: 2 },
	{ string: '3', value: 3 },
	{ string: 'three', value: 3 },
	{ string: '4', value: 4 },
	{ string: 'four', value: 4 },
	{ string: '5', value: 5 },
	{ string: 'five', value: 5 },
	{ string: '6', value: 6 },
	{ string: 'six', value: 6 },
	{ string: '7', value: 7 },
	{ string: 'seven', value: 7 },
	{ string: '8', value: 8 },
	{ string: 'eight', value: 8 },
	{ string: '9', value: 9 },
	{ string: 'nine', value: 9 }
];
